In [1]:
'''
All Variants
'''
import pandas as pd

df_heba = pd.read_csv(r"C:\Users\moham\OneDrive\Desktop\WebScraping\legacy_app\output\heba\heba_variants.csv")
df_nillens = pd.read_csv(r"C:\Users\moham\OneDrive\Desktop\WebScraping\legacy_app\output\nillens\nillens_variants.csv")
df_lilly = pd.read_csv(r"C:\Users\moham\OneDrive\Desktop\WebScraping\legacy_app\output\lilly home\lilly_home_variants.csv")
df_heba

,Variant ID,Handle,Variant,Price,SKU,Scraped at,Availability
0,46336742719779,calligraphy-duvet-set,King / White,14495.0,672b94526d860,2026/02/01 03:57:54 PM,False
1,46635615027491,calligraphy-bath-mat-set,White,4295.0,672b9451e4a21,2026/02/01 03:57:56 PM,False
2,46383258698019,astronauts-swaddle-towel-sets,White,995.0,672b9440b801c,2026/02/01 03:57:58 PM,False
3,46383258763555,astronauts-swaddle-towel-sets,Cream,995.0,672b943fec8b4,2026/02/01 03:57:58 PM,True
4,46867430703395,flow-towels-set,White,2195.0,672b95f9ce279,2026/02/01 03:58:01 PM,False
...,...,...,...,...,...,...,...
72,47052814745891,farashat-guest-towel-set,White,480.0,672b95cb63556,2026/02/01 03:59:16 PM,True
73,47067664351523,farashat-guest-towel-set,Cream,480.0,672b95ca8f539,2026/02/01 03:59:16 PM,True
74,45686430630179,farashat-towels-set-3pcs,White,1795.0,672b95cedc178,2026/02/01 03:59:17 PM,False
75,45686430662947,farashat-towels-set-3pcs,Cream,1795.0,672b95ce287db,2026/02/01 03:59:17 PM,True
76,46635995726115,feather-duvet-set,King / White x Khaki,6995.0,672b95cfea410,2026/02/01 03:59:19 PM,True

In [16]:
df_heba["Brand"] = "Heba Linens"
df_nillens["Brand"] = "Nillens"
df_lilly["Brand"] = "Lilly Home"

df_combined_variants = pd.concat([df_heba, df_nillens, df_lilly], ignore_index=True)
df_combined_variants["Brand + Variant ID"] = df_combined_variants["Brand"] + " #" + df_combined_variants["Variant ID"].astype(str)
df = pd.DataFrame()
df["Brand"] = df_combined_variants["Brand"]
df["Variant ID"] = df_combined_variants["Variant ID"]
df["Variant"] = df_combined_variants["Handle"]
df["Price"] = df_combined_variants["Price"]
df["Availability"] = df_combined_variants["Availability"]
df["SKU"] = df_combined_variants["SKU"]
df["Brand + Variant ID"] = df_combined_variants["Brand + Variant ID"]
df

,Brand,Variant ID,Variant,Price,Availability,SKU,Brand + Variant ID
0,Heba Linens,46336742719779,calligraphy-duvet-set,14495.0,False,672b94526d860,Heba Linens #46336742719779
1,Heba Linens,46635615027491,calligraphy-bath-mat-set,4295.0,False,672b9451e4a21,Heba Linens #46635615027491
2,Heba Linens,46383258698019,astronauts-swaddle-towel-sets,995.0,False,672b9440b801c,Heba Linens #46383258698019
3,Heba Linens,46383258763555,astronauts-swaddle-towel-sets,995.0,True,672b943fec8b4,Heba Linens #46383258763555
4,Heba Linens,46867430703395,flow-towels-set,2195.0,False,672b95f9ce279,Heba Linens #46867430703395
...,...,...,...,...,...,...,...
1516,Lilly Home,41081319522498,bath-mat,720.0,False,lil-Liv-B1-1-2,Lilly Home #41081319522498
1517,Lilly Home,41081319555266,bath-mat,720.0,False,lil-Liv-B1-1-3,Lilly Home #41081319555266
1518,Lilly Home,41081319588034,bath-mat,720.0,False,lil-Liv-B1-1-4,Lilly Home #41081319588034
1519,Lilly Home,41147521466562,half-face,620.0,False,lil-NMG-1-2-1-1-2-1-1-1-1-1-1,Lilly Home #41147521466562
1520,Lilly Home,41147521499330,half-face,620.0,False,lil-NMG-1-2-1-1-2-1-1-1-1-1-2,Lilly Home #41147521499330

In [28]:
# df.to_csv(r"C:\Users\moham\OneDrive\Desktop\WebScraping\legacy_app\output\all\all_variants_add_description.csv")
variant_list = df["Brand + Variant ID"].tolist()
variant_set = set(variant_list)
df.to_csv(r"C:\Users\moham\OneDrive\Desktop\WebScraping\legacy_app\output\all\all_variants_clean.csv")

,Variant ID,Handle,Variant,Price,SKU,Scraped at,Availability,Brand,Brand + Variant ID
0,46336742719779,calligraphy-duvet-set,King / White,14495.0,672b94526d860,2026/02/01 03:57:54 PM,False,Heba Linens,Heba Linens: 46336742719779
1,46635615027491,calligraphy-bath-mat-set,White,4295.0,672b9451e4a21,2026/02/01 03:57:56 PM,False,Heba Linens,Heba Linens: 46635615027491
2,46383258698019,astronauts-swaddle-towel-sets,White,995.0,672b9440b801c,2026/02/01 03:57:58 PM,False,Heba Linens,Heba Linens: 46383258698019
3,46383258763555,astronauts-swaddle-towel-sets,Cream,995.0,672b943fec8b4,2026/02/01 03:57:58 PM,True,Heba Linens,Heba Linens: 46383258763555
4,46867430703395,flow-towels-set,White,2195.0,672b95f9ce279,2026/02/01 03:58:01 PM,False,Heba Linens,Heba Linens: 46867430703395
...,...,...,...,...,...,...,...,...,...
1516,41081319522498,bath-mat,Brown,720.0,lil-Liv-B1-1-2,2026/02/02 01:30:47 PM,False,Lilly Home,Lilly Home: 41081319522498
1517,41081319555266,bath-mat,Genzari,720.0,lil-Liv-B1-1-3,2026/02/02 01:30:47 PM,False,Lilly Home,Lilly Home: 41081319555266
1518,41081319588034,bath-mat,Gray,720.0,lil-Liv-B1-1-4,2026/02/02 01:30:47 PM,False,Lilly Home,Lilly Home: 41081319588034
1519,41147521466562,half-face,Black,620.0,lil-NMG-1-2-1-1-2-1-1-1-1-1-1,2026/02/02 01:32:37 PM,False,Lilly Home,Lilly Home: 41147521466562
1520,41147521499330,half-face,White,620.0,lil-NMG-1-2-1-1-2-1-1-1-1-1-2,2026/02/02 01:32:37 PM,False,Lilly Home,Lilly Home: 41147521499330