In [1]:
import pandas as pd
file = r'C:\Users\moham\OneDrive\Desktop\WebScraping\legacy_app\output\heba\heba_raw.csv'
df = pd.read_csv(file)
df = df.drop(columns=['Accessory size', 'Weight'])
df = df.dropna(subset=['Description'])
df

,Availability,Color,Description,Handle,Inventory Management,Price,Product,Product URL,SKU,Scraped at,Size,Title,Variant,Variant ID
0,True,White,Pack and travel in style with this designer Br...,bra-and-underwear-bag,shopify,395.0,Bra and Underwear bag,https://hebalinens.com/products/bra-and-underw...,672b944f4d8e4,2026/02/11 03:44:25 PM,60 L X 40 W,NaN,White / 60 L X 40 W,46353877205283
1,False,White,Experience the best of both worlds—the luxurio...,flow-towels-set,shopify,2195.0,Flow - Towel Set,https://hebalinens.com/products/flow-towels-set,672b95f9ce279,2026/02/11 03:44:26 PM,NaN,NaN,White,46867430703395
2,False,Grey,Experience the best of both worlds—the luxurio...,flow-towels-set,shopify,2195.0,Flow - Towel Set,https://hebalinens.com/products/flow-towels-set,672b95f9218be,2026/02/11 03:44:26 PM,NaN,NaN,Grey,46867430768931
3,False,White,A beautiful tribute to the legendary singer Om...,calligraphy-duvet-set,shopify,14495.0,Calligraphy - Duvet set,https://hebalinens.com/products/calligraphy-du...,672b94526d860,2026/02/11 03:44:27 PM,King,NaN,King / White,46336742719779
4,True,Cream,Brighten up your dining experience with the ey...,table-cloth-batterflies,shopify,6245.0,Butterflies - Table Cloth,https://hebalinens.com/products/table-cloth-ba...,672b9451e57ce,2026/02/11 03:44:29 PM,2.75 L x 1.8 W with 8 Napkin,NaN,2.75 L x 1.8 W with 8 Napkin / Cream,46344867905827
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
214,True,White,Up your kid's bedding game with this 100% fine...,surfing-duvet-set,shopify,6395.0,Surfing - Duvet set,https://hebalinens.com/products/surfing-duvet-set,672b9786df02c,2026/02/11 03:47:38 PM,Single,NaN,Single / White,46381930807587
215,True,White,Experience the luxuriously soft feel of the Tr...,trio-sheet-set-6pcs,shopify,6295.0,Trio - Sheet Set,https://hebalinens.com/products/trio-sheet-set...,672b97a1bfc85,2026/02/11 03:47:40 PM,King,NaN,King / White,45687685349667
216,True,Silver,Experience the luxuriously soft feel of the Tr...,trio-sheet-set-6pcs,shopify,6295.0,Trio - Sheet Set,https://hebalinens.com/products/trio-sheet-set...,672b97a11483d,2026/02/11 03:47:40 PM,King,NaN,King / Silver,45704160870691
217,True,White,Experience luxurious cotton softness with our ...,trio-towel-set-3pcs,shopify,1995.0,Trio - Towel Set,https://hebalinens.com/products/trio-towel-set...,672b97a250ed8,2026/02/11 03:47:41 PM,NaN,NaN,White,45688064442659
218,False,Silver,Experience luxurious cotton softness with our ...,trio-towel-set-3pcs,shopify,1995.0,Trio - Towel Set,https://hebalinens.com/products/trio-towel-set...,672b97a1870a1,2026/02/11 03:47:41 PM,NaN,NaN,Silver,45704165622051

In [2]:
import pandas as pd

# 1. Clean the 'Description' column BEFORE merging to remove new lines
df['Description'] = df['Description'].str.replace(r'\n|\r', ' ', regex=True)

# 2. Updated aggregation rules to create clean strings instead of Python lists
# We use ', '.join() to make "White, Cream" instead of "['White', 'Cream']"
aggregation_rules = {
    'Title': lambda x: ', '.join(map(str, x.unique())),
    'Variant': lambda x: ', '.join(map(str, x.unique())), 
    'Variant ID': lambda x: ', '.join(map(str, x.unique())),
    'SKU': lambda x: ', '.join(map(str, x.unique())),
    'Size': lambda x: ', '.join(map(str, x.unique())),
    'Inventory Management': 'first',
    'Handle': 'first',
    'Availability': 'first',
    'Product URL': 'first',
    'Scraped at': 'first'
}

# Group by the "Core" identity
df_merged = df.groupby(['Product', 'Description', 'Price'], as_index=False).agg(aggregation_rules)

# 3. FIX: Create the Hollistic Description correctly
# Use .astype(str) instead of str() to handle it row-by-row
df_merged['Hollistic Description'] = (
    df_merged['Product'] + 
    ' - ' + 
    df_merged['Variant'].astype(str) + 
    ": " + 
    df_merged["Description"]
)

# Reorder columns
columns_order = [
    'Product', 'Title', 'Variant', 'Price', 'Handle', 
    'Inventory Management', 'Variant ID', 'Availability', 'SKU', 
    'Product URL', 'Scraped at', 'Size',
    'Description', 'Hollistic Description'
]
df_merged = df_merged[columns_order]

# Save to CSV (index=False prevents that extra "0, 1, 2" column at the start)
df_merged = df_merged.drop(columns=['Title', 'Size'])
df_merged.to_csv(r'C:\Users\moham\OneDrive\Desktop\WebScraping\legacy_app\output\heba\heba_compact_view.csv', index=False)
df_merged

,Product,Variant,Price,Handle,Inventory Management,Variant ID,Availability,SKU,Product URL,Scraped at,Description,Hollistic Description
0,Astronauts - Swaddle Towel sets,"White, Cream",995.0,astronauts-swaddle-towel-sets,shopify,"46383258698019, 46383258763555",False,"672b9440b801c, 672b943fec8b4",https://hebalinens.com/products/astronauts-swa...,2026/02/11 03:44:43 PM,Snuggle your little space explorer with our As...,"Astronauts - Swaddle Towel sets - White, Cream..."
1,Atraction - Pouch,Grey / 14 L X 18 W,495.0,atraction-pouch,shopify,54675384008995,True,nan,https://hebalinens.com/products/atraction-pouch,2026/02/11 03:44:40 PM,This charming Pouch instantly adds a touch of ...,Atraction - Pouch - Grey / 14 L X 18 W: This c...
2,Baby animals - Swaddle Towel sets,"White, Cream",995.0,baby-animals-swaddle-towel-sets,shopify,"46383232647459, 46383232712995",False,"672b9440b0b7a, 672b943fe31db",https://hebalinens.com/products/baby-animals-s...,2026/02/11 03:44:47 PM,"Soft and cuddly, this baby swaddle towel set w...","Baby animals - Swaddle Towel sets - White, Cre..."
3,Ballerina - Bath robe,4 years to 6 years / White,645.0,ballerina-bath-robe,shopify,46381868187939,True,672b943feffbe,https://hebalinens.com/products/ballerina-bath...,2026/02/11 03:44:48 PM,"Introducing Ballerina, the perfect 100% cotton...",Ballerina - Bath robe - 4 years to 6 years / W...
4,Ballerina - Bath robe,6 years to 8 years / White,945.0,ballerina-bath-robe,shopify,46381868253475,False,672b9440ad92d,https://hebalinens.com/products/ballerina-bath...,2026/02/11 03:44:48 PM,"Introducing Ballerina, the perfect 100% cotton...",Ballerina - Bath robe - 6 years to 8 years / W...
...,...,...,...,...,...,...,...,...,...,...,...,...
132,Tennis - Duvet set,White,6395.0,tennis-duvet-set,shopify,46382534721827,False,672b9792ec679,https://hebalinens.com/products/tennis-duvet-set,2026/02/11 03:47:29 PM,Inspire a love of sports in your kids with thi...,Tennis - Duvet set - White: Inspire a love of ...
133,Trio - Bath Mat Set,"White, Silver",3995.0,trio-bathmats,shopify,"45704184135971, 45704184168739",True,"672b979d4d9b1, 672b979c8f0dd",https://hebalinens.com/products/trio-bathmats,2026/02/11 03:47:23 PM,Transform your bathroom into a luxurious sanct...,"Trio - Bath Mat Set - White, Silver: Transform..."
134,Trio - Duvet Set,"King / White, King / Silver",7995.0,trio-duvet-set-6pcs,shopify,"45687657464099, 45704157790499",True,"672b979e1ec5b, 672b979d64fd1",https://hebalinens.com/products/trio-duvet-set...,2026/02/11 03:47:28 PM,Adorn your bedroom with the class of ancient E...,"Trio - Duvet Set - King / White, King / Silver..."
135,Trio - Sheet Set,"King / White, King / Silver",6295.0,trio-sheet-set-6pcs,shopify,"45687685349667, 45704160870691",True,"672b97a1bfc85, 672b97a11483d",https://hebalinens.com/products/trio-sheet-set...,2026/02/11 03:47:40 PM,Experience the luxuriously soft feel of the Tr...,"Trio - Sheet Set - King / White, King / Silver..."
136,Trio - Towel Set,"White, Silver",1995.0,trio-towel-set-3pcs,shopify,"45688064442659, 45704165622051",True,"672b97a250ed8, 672b97a1870a1",https://hebalinens.com/products/trio-towel-set...,2026/02/11 03:47:41 PM,Experience luxurious cotton softness with our ...,"Trio - Towel Set - White, Silver: Experience l..."

In [19]:
'''
Products Table
'''
df_products = df_merged
df_products = df_products.drop(columns=['Variant', 'Variant ID', 'Availability'])

# Split by comma and strip whitespace from each element
# 1. First, split the strings into lists (if you haven't already)
df_products['SKUs'] = df_products['SKU'].str.split(',')

# 2. Grab the first element of each list and strip whitespace
df_products['SKU'] = df_products['SKUs'].str[0].str.strip()
# 1. Clean up the decimals and whitespace within the lists first
# This removes '.0' and extra spaces from every item in every list
df_products['SKUs'] = df_products['SKUs'].apply(lambda x: [i.replace('.0', '').strip() for i in x])

# 2. Join the list elements into a single string separated by a space
df_products['SKUs'] = df_products['SKUs'].str.join(' ')

df_products.to_csv(r'C:\Users\moham\OneDrive\Desktop\WebScraping\legacy_app\output\heba\heba_products.csv', index=False)
df_products

,Product,Price,Handle,Inventory Management,SKU,Product URL,Scraped at,Description,Hollistic Description,SKUs
0,Astronauts - Swaddle Towel sets,995.0,astronauts-swaddle-towel-sets,shopify,672b9440b801c,https://hebalinens.com/products/astronauts-swa...,2026/02/11 03:44:43 PM,Snuggle your little space explorer with our As...,"Astronauts - Swaddle Towel sets - White, Cream...",672b9440b801c 672b943fec8b4
1,Atraction - Pouch,495.0,atraction-pouch,shopify,nan,https://hebalinens.com/products/atraction-pouch,2026/02/11 03:44:40 PM,This charming Pouch instantly adds a touch of ...,Atraction - Pouch - Grey / 14 L X 18 W: This c...,nan
2,Baby animals - Swaddle Towel sets,995.0,baby-animals-swaddle-towel-sets,shopify,672b9440b0b7a,https://hebalinens.com/products/baby-animals-s...,2026/02/11 03:44:47 PM,"Soft and cuddly, this baby swaddle towel set w...","Baby animals - Swaddle Towel sets - White, Cre...",672b9440b0b7a 672b943fe31db
3,Ballerina - Bath robe,645.0,ballerina-bath-robe,shopify,672b943feffbe,https://hebalinens.com/products/ballerina-bath...,2026/02/11 03:44:48 PM,"Introducing Ballerina, the perfect 100% cotton...",Ballerina - Bath robe - 4 years to 6 years / W...,672b943feffbe
4,Ballerina - Bath robe,945.0,ballerina-bath-robe,shopify,672b9440ad92d,https://hebalinens.com/products/ballerina-bath...,2026/02/11 03:44:48 PM,"Introducing Ballerina, the perfect 100% cotton...",Ballerina - Bath robe - 6 years to 8 years / W...,672b9440ad92d
...,...,...,...,...,...,...,...,...,...,...
132,Tennis - Duvet set,6395.0,tennis-duvet-set,shopify,672b9792ec679,https://hebalinens.com/products/tennis-duvet-set,2026/02/11 03:47:29 PM,Inspire a love of sports in your kids with thi...,Tennis - Duvet set - White: Inspire a love of ...,672b9792ec679
133,Trio - Bath Mat Set,3995.0,trio-bathmats,shopify,672b979d4d9b1,https://hebalinens.com/products/trio-bathmats,2026/02/11 03:47:23 PM,Transform your bathroom into a luxurious sanct...,"Trio - Bath Mat Set - White, Silver: Transform...",672b979d4d9b1 672b979c8f0dd
134,Trio - Duvet Set,7995.0,trio-duvet-set-6pcs,shopify,672b979e1ec5b,https://hebalinens.com/products/trio-duvet-set...,2026/02/11 03:47:28 PM,Adorn your bedroom with the class of ancient E...,"Trio - Duvet Set - King / White, King / Silver...",672b979e1ec5b 672b979d64fd1
135,Trio - Sheet Set,6295.0,trio-sheet-set-6pcs,shopify,672b97a1bfc85,https://hebalinens.com/products/trio-sheet-set...,2026/02/11 03:47:40 PM,Experience the luxuriously soft feel of the Tr...,"Trio - Sheet Set - King / White, King / Silver...",672b97a1bfc85 672b97a11483d
136,Trio - Towel Set,1995.0,trio-towel-set-3pcs,shopify,672b97a250ed8,https://hebalinens.com/products/trio-towel-set...,2026/02/11 03:47:41 PM,Experience luxurious cotton softness with our ...,"Trio - Towel Set - White, Silver: Experience l...",672b97a250ed8 672b97a1870a1

In [22]:
'''
Variants Table
'''

df_variants = df
df_variants = df_variants.drop(columns=['Product', "Product URL", 'Description'])
cols_to_move = ['Variant ID', 'Handle', 'Variant', 'Price', 'SKU', 'Scraped at']

# Get the list of all other columns that aren't in the "move" list
remaining_cols = [c for c in df_variants.columns if c not in cols_to_move]

# Reorder with move-list first, then the rest
df_variants = df[cols_to_move + remaining_cols]
df_variants = df_variants.drop(columns=['Size', 'Title'])
df_variants.to_csv(r'C:\Users\moham\OneDrive\Desktop\WebScraping\legacy_app\output\heba\heba_variants.csv', index=False)
print(r'Successfully printed to legacy_app\output\heba\heba_variants.csv')
df_variants

Successfully printed to legacy_app\output\heba\heba_variants.csv

,Variant ID,Handle,Variant,Price,SKU,Scraped at,Availability,Color,Inventory Management
0,46353877205283,bra-and-underwear-bag,White / 60 L X 40 W,395.0,672b944f4d8e4,2026/02/11 03:44:25 PM,True,White,shopify
1,46867430703395,flow-towels-set,White,2195.0,672b95f9ce279,2026/02/11 03:44:26 PM,False,White,shopify
2,46867430768931,flow-towels-set,Grey,2195.0,672b95f9218be,2026/02/11 03:44:26 PM,False,Grey,shopify
3,46336742719779,calligraphy-duvet-set,King / White,14495.0,672b94526d860,2026/02/11 03:44:27 PM,False,White,shopify
4,46344867905827,table-cloth-batterflies,2.75 L x 1.8 W with 8 Napkin / Cream,6245.0,672b9451e57ce,2026/02/11 03:44:29 PM,True,Cream,shopify
...,...,...,...,...,...,...,...,...,...
214,46381930807587,surfing-duvet-set,Single / White,6395.0,672b9786df02c,2026/02/11 03:47:38 PM,True,White,shopify
215,45687685349667,trio-sheet-set-6pcs,King / White,6295.0,672b97a1bfc85,2026/02/11 03:47:40 PM,True,White,shopify
216,45704160870691,trio-sheet-set-6pcs,King / Silver,6295.0,672b97a11483d,2026/02/11 03:47:40 PM,True,Silver,shopify
217,45688064442659,trio-towel-set-3pcs,White,1995.0,672b97a250ed8,2026/02/11 03:47:41 PM,True,White,shopify
218,45704165622051,trio-towel-set-3pcs,Silver,1995.0,672b97a1870a1,2026/02/11 03:47:41 PM,False,Silver,shopify