In [12]:
import pandas as pd
file = r'C:\Users\moham\OneDrive\Desktop\WebScraping\legacy_app\output\Lilly Home\lily_home_raw.csv'
df = pd.read_csv(file)
df = df.drop(columns=['Weight', 'size', 'Style'])
df = df.dropna(subset=['Description'])
df['Title'] = 'N/A'
print(df.shape)
df

(989, 14)

,Availability,Color,Description,Handle,Inventory Management,Price,Product,Product URL,SKU,Scraped at,Size,Variant,Variant ID,Title
0,True,white,A 100% Egyptian Cotton High absorption\n3 piec...,1-line-towel-set-3-pcs,NaN,1880.0,1 line Towel set (3 pcs),https://eg.lilly-home.com//products/1-line-tow...,NaN,2026/02/11 04:40:49 PM,NaN,white,44364304974018,N/A
1,True,cafè,A 100% Egyptian Cotton High absorption\n3 piec...,1-line-towel-set-3-pcs,NaN,1880.0,1 line Towel set (3 pcs),https://eg.lilly-home.com//products/1-line-tow...,NaN,2026/02/11 04:40:49 PM,NaN,cafè,44364327551170,N/A
2,True,white,100% egyptian cotton\nsizes:\nHand Towel: 50x1...,1-line-jacquard-towel,shopify,480.0,1 Line Jacquard Towel,https://eg.lilly-home.com//products/1-line-jac...,NaN,2026/02/11 04:40:51 PM,Hand towel,Hand towel / white,44613386830018,N/A
3,True,Coal,100% egyptian cotton\nsizes:\nHand Towel: 50x1...,1-line-jacquard-towel,shopify,480.0,1 Line Jacquard Towel,https://eg.lilly-home.com//products/1-line-jac...,NaN,2026/02/11 04:40:51 PM,Hand towel,Hand towel / Coal,44613390401730,N/A
4,True,white,100% egyptian cotton\nsizes:\nHand Towel: 50x1...,1-line-jacquard-towel,shopify,740.0,1 Line Jacquard Towel,https://eg.lilly-home.com//products/1-line-jac...,NaN,2026/02/11 04:40:51 PM,Face Towel,Face Towel / white,44613386895554,N/A
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
989,True,Coal,100% egyptian cotton\nsizes:\nHand Towel: 50x1...,squares-jacquard-towel-copy,NaN,980.0,Zigzag Jacquard Towel,https://eg.lilly-home.com//products/squares-ja...,NaN,2026/02/11 04:45:55 PM,Bath Towel,Bath Towel / Coal,44613384634562,N/A
990,True,Beige,\nA one piece knitted wool throw\n150 x 230 cm,zigzag-knitted-throw-copy,NaN,2400.0,Zigzag Knitted throw,https://eg.lilly-home.com//products/zigzag-kni...,NaN,2026/02/11 04:45:57 PM,NaN,Beige,44858298663106,N/A
991,True,Cafe,\nA one piece knitted wool throw\n150 x 230 cm,zigzag-knitted-throw-copy,NaN,2400.0,Zigzag Knitted throw,https://eg.lilly-home.com//products/zigzag-kni...,NaN,2026/02/11 04:45:57 PM,NaN,Cafe,44858298695874,N/A
992,True,Coal,\nA one piece knitted wool throw\n150 x 230 cm,zigzag-knitted-throw-copy,NaN,2400.0,Zigzag Knitted throw,https://eg.lilly-home.com//products/zigzag-kni...,NaN,2026/02/11 04:45:57 PM,NaN,Coal,44858298564802,N/A
993,True,Black,\nA one piece knitted wool throw\n150 x 230 cm,zigzag-knitted-throw-copy,NaN,2400.0,Zigzag Knitted throw,https://eg.lilly-home.com//products/zigzag-kni...,NaN,2026/02/11 04:45:57 PM,NaN,Black,44858298499266,N/A

In [15]:
import pandas as pd

# 1. Clean the 'Description' column BEFORE merging to remove new lines
df['Description'] = df['Description'].str.replace(r'\n|\r', ' ', regex=True)

# 2. Updated aggregation rules to create clean strings instead of Python lists
# We use ', '.join() to make "White, Cream" instead of "['White', 'Cream']"
aggregation_rules = {
    'Title': lambda x: ', '.join(map(str, x.unique())),
    'Variant': lambda x: ', '.join(map(str, x.unique())), 
    'Variant ID': lambda x: ', '.join(map(str, x.unique())),
    'SKU': lambda x: ', '.join(map(str, x.unique())),
    'Size': lambda x: ', '.join(map(str, x.unique())),
    'Inventory Management': 'first',
    'Handle': 'first',
    'Availability': 'first',
    'Product URL': 'first',
    'Scraped at': 'first'
}

# Group by the "Core" identity
df_merged = df.groupby(['Product', 'Description', 'Price'], as_index=False).agg(aggregation_rules)

# 3. FIX: Create the Hollistic Description correctly
# Use .astype(str) instead of str() to handle it row-by-row
df_merged['Hollistic Description'] = (
    df_merged['Product'] + 
    ' - ' + 
    df_merged['Variant'].astype(str) + 
    ": " + 
    df_merged["Description"]
)

# Reorder columns
columns_order = [
    'Product', 'Title', 'Variant', 'Price', 'Handle', 
    'Inventory Management', 'Variant ID', 'Availability', 'SKU', 
    'Product URL', 'Scraped at', 'Size',
    'Description', 'Hollistic Description'
]
df_merged = df_merged[columns_order]

# Save to CSV (index=False prevents that extra "0, 1, 2" column at the start)
df_merged = df_merged.drop(columns=['Title', 'Size'])
df_merged.to_csv(r'C:\Users\moham\OneDrive\Desktop\WebScraping\legacy_app\output\Lilly Home\lilly_home_compact_view.csv', index=False)
df_merged

,Product,Variant,Price,Handle,Inventory Management,Variant ID,Availability,SKU,Product URL,Scraped at,Description,Hollistic Description
0,1 Line Jacquard Towel,"Hand towel / white, Hand towel / Coal",480.0,1-line-jacquard-towel,shopify,"44613386830018, 44613390401730",True,nan,https://eg.lilly-home.com//products/1-line-jac...,2026/02/11 04:40:51 PM,100% egyptian cotton sizes: Hand Towel: 50x100...,"1 Line Jacquard Towel - Hand towel / white, Ha..."
1,1 Line Jacquard Towel,"Face Towel / white, Face Towel / Coal",740.0,1-line-jacquard-towel,shopify,"44613386895554, 44613390434498",True,nan,https://eg.lilly-home.com//products/1-line-jac...,2026/02/11 04:40:51 PM,100% egyptian cotton sizes: Hand Towel: 50x100...,"1 Line Jacquard Towel - Face Towel / white, Fa..."
2,1 Line Jacquard Towel,"Bath Towel / white, Bath Towel / Coal",980.0,1-line-jacquard-towel,shopify,"44613386961090, 44613390467266",True,nan,https://eg.lilly-home.com//products/1-line-jac...,2026/02/11 04:40:51 PM,100% egyptian cotton sizes: Hand Towel: 50x100...,"1 Line Jacquard Towel - Bath Towel / white, Ba..."
3,1 line Towel set (3 pcs),"white, cafè",1880.0,1-line-towel-set-3-pcs,None,"44364304974018, 44364327551170",True,nan,https://eg.lilly-home.com//products/1-line-tow...,2026/02/11 04:40:49 PM,A 100% Egyptian Cotton High absorption 3 piece...,"1 line Towel set (3 pcs) - white, cafè: A 100%..."
4,100% Linen Chemise,"S / Pink, S / Navy Blue, S / Green, S / yellow...",2010.0,set-short-and-chemise,shopify,"41127631880386, 42257359700162, 42257359732930...",True,nan,https://eg.lilly-home.com//products/set-short-...,2026/02/11 04:40:52 PM,Material: 100% Linen,"100% Linen Chemise - S / Pink, S / Navy Blue, ..."
...,...,...,...,...,...,...,...,...,...,...,...,...
217,knitted Set,"small / white, small / Beige, medium / white, ...",2280.0,knitted-set,shopify,"44556089884866, 44556090998978, 44556089917634...",True,nan,https://eg.lilly-home.com//products/knitted-set,2026/02/11 04:43:35 PM,2 pieces knittedlounge wear set :-,"knitted Set - small / white, small / Beige, me..."
218,lines duvet cover Set (3pcs),"king / white, king / brown, queen / white, que...",4620.0,lines-duvet-cover-set-3pcs,None,"42986164682946, 42986164715714, 42986164748482...",True,nan,https://eg.lilly-home.com//products/lines-duve...,2026/02/11 04:44:20 PM,A 3 piece400 thread count 100% egyptian cott...,"lines duvet cover Set (3pcs) - king / white, k..."
219,stones duvet cover Set (3pcs),"king / white, king / beige, queen / white, que...",4620.0,stones-duvet-cover-set-3pcs,None,"42986153476290, 42986161635522, 42986153509058...",True,nan,https://eg.lilly-home.com//products/stones-duv...,2026/02/11 04:45:16 PM,A 3 piece400 thread count 100% egyptian cott...,"stones duvet cover Set (3pcs) - king / white, ..."
220,tri duvet cover Set (3pcs),"king / white, king / brown, queen / white, que...",4620.0,tri-duvet-cover-set-3pcs,None,"42986161963202, 42986161995970, 42986162028738...",True,nan,https://eg.lilly-home.com//products/tri-duvet-...,2026/02/11 04:45:38 PM,A 3 piece400 thread count 100% egyptian cotto...,"tri duvet cover Set (3pcs) - king / white, kin..."
221,zigzag 78 Towel set (3 pcs),"white, silver, cafe, grey",1880.0,zigzag-78-towel-set-6-pcs,None,"42780865003714, 42780865036482, 42780865069250...",True,nan,https://eg.lilly-home.com//products/zigzag-78-...,2026/02/11 04:45:49 PM,A 100% Egyptian Cotton High absorption 3 piece...,"zigzag 78 Towel set (3 pcs) - white, silver, c..."

In [27]:
'''
Products Table
'''
df_products = df_merged
df_products = df_products.drop(columns=['Variant', 'Variant ID', 'Availability'])

# Split by comma and strip whitespace from each element
# 1. First, split the strings into lists (if you haven't already)
df_products['SKUs'] = df_products['SKU'].str.split(',')

# 2. Grab the first element of each list and strip whitespace
df_products['SKU'] = df_products['SKUs'].str[0].str.strip()
# 1. Clean up the decimals and whitespace within the lists first
# This removes '.0' and extra spaces from every item in every list
df_products['SKUs'] = df_products['SKUs'].apply(lambda x: [i.replace('.0', '').strip() for i in x])

# 2. Join the list elements into a single string separated by a space
df_products['SKUs'] = df_products['SKUs'].str.join(' ')

df_products['SKU'] = 'N/A'
df_products['SKUs'] = 'N/A'
df_products.to_csv(r'C:\Users\moham\OneDrive\Desktop\WebScraping\legacy_app\output\Lilly Home\lilly_home_products.csv', index=False)
df_products

,Product,Price,Handle,Inventory Management,SKU,Product URL,Scraped at,Description,Hollistic Description,SKUs
0,1 Line Jacquard Towel,480.0,1-line-jacquard-towel,shopify,N/A,https://eg.lilly-home.com//products/1-line-jac...,2026/02/11 04:40:51 PM,100% egyptian cotton sizes: Hand Towel: 50x100...,"1 Line Jacquard Towel - Hand towel / white, Ha...",N/A
1,1 Line Jacquard Towel,740.0,1-line-jacquard-towel,shopify,N/A,https://eg.lilly-home.com//products/1-line-jac...,2026/02/11 04:40:51 PM,100% egyptian cotton sizes: Hand Towel: 50x100...,"1 Line Jacquard Towel - Face Towel / white, Fa...",N/A
2,1 Line Jacquard Towel,980.0,1-line-jacquard-towel,shopify,N/A,https://eg.lilly-home.com//products/1-line-jac...,2026/02/11 04:40:51 PM,100% egyptian cotton sizes: Hand Towel: 50x100...,"1 Line Jacquard Towel - Bath Towel / white, Ba...",N/A
3,1 line Towel set (3 pcs),1880.0,1-line-towel-set-3-pcs,None,N/A,https://eg.lilly-home.com//products/1-line-tow...,2026/02/11 04:40:49 PM,A 100% Egyptian Cotton High absorption 3 piece...,"1 line Towel set (3 pcs) - white, cafè: A 100%...",N/A
4,100% Linen Chemise,2010.0,set-short-and-chemise,shopify,N/A,https://eg.lilly-home.com//products/set-short-...,2026/02/11 04:40:52 PM,Material: 100% Linen,"100% Linen Chemise - S / Pink, S / Navy Blue, ...",N/A
...,...,...,...,...,...,...,...,...,...,...
217,knitted Set,2280.0,knitted-set,shopify,N/A,https://eg.lilly-home.com//products/knitted-set,2026/02/11 04:43:35 PM,2 pieces knittedlounge wear set :-,"knitted Set - small / white, small / Beige, me...",N/A
218,lines duvet cover Set (3pcs),4620.0,lines-duvet-cover-set-3pcs,None,N/A,https://eg.lilly-home.com//products/lines-duve...,2026/02/11 04:44:20 PM,A 3 piece400 thread count 100% egyptian cott...,"lines duvet cover Set (3pcs) - king / white, k...",N/A
219,stones duvet cover Set (3pcs),4620.0,stones-duvet-cover-set-3pcs,None,N/A,https://eg.lilly-home.com//products/stones-duv...,2026/02/11 04:45:16 PM,A 3 piece400 thread count 100% egyptian cott...,"stones duvet cover Set (3pcs) - king / white, ...",N/A
220,tri duvet cover Set (3pcs),4620.0,tri-duvet-cover-set-3pcs,None,N/A,https://eg.lilly-home.com//products/tri-duvet-...,2026/02/11 04:45:38 PM,A 3 piece400 thread count 100% egyptian cotto...,"tri duvet cover Set (3pcs) - king / white, kin...",N/A
221,zigzag 78 Towel set (3 pcs),1880.0,zigzag-78-towel-set-6-pcs,None,N/A,https://eg.lilly-home.com//products/zigzag-78-...,2026/02/11 04:45:49 PM,A 100% Egyptian Cotton High absorption 3 piece...,"zigzag 78 Towel set (3 pcs) - white, silver, c...",N/A

In [37]:
'''
Variants Table
'''

df_variants = df
df_variants = df_variants.drop(columns=['Product', "Product URL", 'Description'])
cols_to_move = ['Variant ID', 'Handle', 'Variant', 'Price', 'SKU', 'Scraped at']

# Get the list of all other columns that aren't in the "move" list
remaining_cols = [c for c in df_variants.columns if c not in cols_to_move]

# Reorder with move-list first, then the rest
df_variants = df[cols_to_move + remaining_cols]
df_variants = df_variants.drop(columns=['Size', 'Title'])
df_variants['SKU'] = 'N/A'
df_variants['Inventory Management'] = df_variants['Inventory Management'].fillna('N/A')
df_variants.to_csv(r'C:\Users\moham\OneDrive\Desktop\WebScraping\legacy_app\output\Lilly Home\lilly_home_variants.csv', index=False)
print(r'Successfully printed to legacy_app\output\heba\lilly_home_variants.csv')
df_variants

Successfully printed to legacy_app\output\heba\lilly_home_variants.csv

,Variant ID,Handle,Variant,Price,SKU,Scraped at,Availability,Color,Inventory Management
0,44364304974018,1-line-towel-set-3-pcs,white,1880.0,N/A,2026/02/11 04:40:49 PM,True,white,N/A
1,44364327551170,1-line-towel-set-3-pcs,cafè,1880.0,N/A,2026/02/11 04:40:49 PM,True,cafè,N/A
2,44613386830018,1-line-jacquard-towel,Hand towel / white,480.0,N/A,2026/02/11 04:40:51 PM,True,white,shopify
3,44613390401730,1-line-jacquard-towel,Hand towel / Coal,480.0,N/A,2026/02/11 04:40:51 PM,True,Coal,shopify
4,44613386895554,1-line-jacquard-towel,Face Towel / white,740.0,N/A,2026/02/11 04:40:51 PM,True,white,shopify
...,...,...,...,...,...,...,...,...,...
989,44613384634562,squares-jacquard-towel-copy,Bath Towel / Coal,980.0,N/A,2026/02/11 04:45:55 PM,True,Coal,N/A
990,44858298663106,zigzag-knitted-throw-copy,Beige,2400.0,N/A,2026/02/11 04:45:57 PM,True,Beige,N/A
991,44858298695874,zigzag-knitted-throw-copy,Cafe,2400.0,N/A,2026/02/11 04:45:57 PM,True,Cafe,N/A
992,44858298564802,zigzag-knitted-throw-copy,Coal,2400.0,N/A,2026/02/11 04:45:57 PM,True,Coal,N/A
993,44858298499266,zigzag-knitted-throw-copy,Black,2400.0,N/A,2026/02/11 04:45:57 PM,True,Black,N/A