In [2]:
import pandas as pd
file = r'C:\Users\moham\WebScraping\legacy_app\output\ninos_kids\ninos.csv'
df = pd.read_csv(file)
df = df.rename({'Variant Title': 'Variant'}, axis='columns')
df

,Product,Handle,Price,SKU,Availability,Variant,Variant ID,Weight,Inventory Management,Product URL,Scraped at,Description
0,1.88m x 71cm Fashion Lounge,1-88m-x-71cm-fashion-lounge,399.0,140214-S23-43040W,False,White / Free,41562102792401,0,shopify,https://www.ninoskids.com/en/products/1-88m-x-...,2026/02/23 02:05:58 PM,Introducing the ultimate summer essential - th...
1,1.88m x 71cm Fashion Lounge,1-88m-x-71cm-fashion-lounge-2,399.0,140214-S23-43040F,False,Fuscia / Free,41562102857937,0,shopify,https://www.ninoskids.com/en/products/1-88m-x-...,2026/02/23 02:05:59 PM,Introducing the ultimate poolside accessory - ...
2,1.83m x H38cm Fill 'N Fun Odyssey Pool,1-83m-x-h38cm-fill-n-fun-odyssey-pool,849.0,140214-S23-55030,False,Blue / Free,41562173898961,0,shopify,https://www.ninoskids.com/en/products/1-83m-x-...,2026/02/23 02:06:00 PM,"""Add a splash of fun to your backyard with our..."
3,1.65m Splash Pad SpiderMan,1-65m-splash-pad-spiderman,999.0,140214-S23-98792,False,Navy / Free,41562241237201,0,shopify,https://www.ninoskids.com/en/products/1-65m-sp...,2026/02/23 02:06:01 PM,Introducing the ultimate summer accessory for ...
4,1.07m Geometric Swim Ring,1-07m-geometric-swim-ring,385.0,140214-S23-36228W,False,White / Free,41562079101137,0,shopify,https://www.ninoskids.com/en/products/1-07m-ge...,2026/02/23 02:06:02 PM,Add some geometric fun to your pool days with ...
...,...,...,...,...,...,...,...,...,...,...,...,...
9724,كوب مانع للتسرب+6,%D9%83%D9%88%D8%A8-%D9%85%D8%A7%D9%86%D8%B9-%D...,350.0,414-S22-35/208,True,Blue / Free,42898370986193,0,shopify,https://www.ninoskids.com/en/products/%D9%83%D...,2026/02/23 02:35:36 PM,"Introducing our leak-proof cup, a must-have fo..."
9725,ملعقة سيليكون بيد ربر الوان,%D9%85%D9%84%D8%B9%D9%82%D8%A9-%D8%B3%D9%8A%D9...,225.0,414-R23-21/488,False,Mix Color / Free,42445153075409,0,shopify,https://www.ninoskids.com/en/products/%D9%85%D...,2026/02/23 02:35:38 PM,NaN
9726,مقص كانبول بجراب الوان,%D9%85%D9%82%D8%B5-%D9%83%D8%A7%D9%86%D8%A8%D9...,225.0,414-R-2/809,True,Default Title,41026652242129,0,shopify,https://www.ninoskids.com/en/products/%D9%85%D...,2026/02/23 02:35:39 PM,NaN
9727,مقص لافروتا,%D9%85%D9%82%D8%B5-%D9%84%D8%A7%D9%81%D8%B1%D9...,95.0,414-R-22642,True,Default Title,41026615050449,0,shopify,https://www.ninoskids.com/en/products/%D9%85%D...,2026/02/23 02:35:40 PM,NaN
9728,وسائد ثدي ترو القطنية 30 قطعة,%D9%88%D8%B3%D8%A7%D8%A6%D8%AF-%D8%AB%D8%AF%D9...,190.0,414-R23-18920TR,True,Mix Color / Free,41512961474769,0,shopify,https://www.ninoskids.com/en/products/%D9%88%D...,2026/02/23 02:35:41 PM,"Introducing the Tru Cotton Breast Pads, a must..."

In [5]:
import pandas as pd

# 1. Clean the 'Description' column BEFORE merging to remove new lines
df['Description'] = df['Description'].str.replace(r'\n|\r', ' ', regex=True)

# 2. Updated aggregation rules to create clean strings instead of Python lists
# We use ', '.join() to make "White, Cream" instead of "['White', 'Cream']"
aggregation_rules = {
    # 'Title': lambda x: ', '.join(map(str, x.unique())),
    'Variant': lambda x: ', '.join(map(str, x.unique())), 
    'Variant ID': lambda x: ', '.join(map(str, x.unique())),
    'SKU': lambda x: ', '.join(map(str, x.unique())),
    # 'Size': lambda x: ', '.join(map(str, x.unique())),
    'Inventory Management': 'first',
    'Handle': 'first',
    'Availability': 'first',
    'Product URL': 'first',
    'Scraped at': 'first'
}

# Group by the "Core" identity
df_merged = df.groupby(['Product', 'Description', 'Price'], as_index=False).agg(aggregation_rules)

# 3. FIX: Create the Hollistic Description correctly
# Use .astype(str) instead of str() to handle it row-by-row
df_merged['Hollistic Description'] = (
    df_merged['Product'] + 
    ' - ' + 
    df_merged['Variant'].astype(str) + 
    ": " + 
    df_merged["Description"]
)

# Save to CSV (index=False prevents that extra "0, 1, 2" column at the start)
print(df_merged.columns)
df_merged.to_csv(r'C:\Users\moham\WebScraping\legacy_app\output\ninos_kids\ninos_compact.csv', index=False)
df_merged

Index(['Product', 'Description', 'Price', 'Variant', 'Variant ID', 'SKU',
       'Inventory Management', 'Handle', 'Availability', 'Product URL',
       'Scraped at', 'Hollistic Description'],
      dtype='object')

,Product,Description,Price,Variant,Variant ID,SKU,Inventory Management,Handle,Availability,Product URL,Scraped at,Hollistic Description
0,1.07m Geometric Swim Ring,Add some geometric fun to your pool days with ...,385.0,White / Free,41562079101137,140214-S23-36228W,shopify,1-07m-geometric-swim-ring,False,https://www.ninoskids.com/en/products/1-07m-ge...,2026/02/23 02:06:02 PM,1.07m Geometric Swim Ring - White / Free: Add ...
1,1.19m x 79cm Happy Crustacean Junior Raft,Get ready for a splashing good time with our H...,479.0,Turquiose / Free,41561373409489,140214-S23-34009,shopify,1-19m-x-79cm-happy-crustacean-junior-raft,False,https://www.ninoskids.com/en/products/1-19m-x-...,2026/02/23 02:06:04 PM,1.19m x 79cm Happy Crustacean Junior Raft - Tu...
2,1.1L Lunch Box with Tray,Our 3-piece lunch set is an essential for busy...,147.0,Black / 1.1L,42671366209745,363137-NOS-6441,shopify,1-1l-lunch-box-with-tray-2,False,https://www.ninoskids.com/en/products/1-1l-lun...,2026/02/23 02:06:07 PM,1.1L Lunch Box with Tray - Black / 1.1L: Our 3...
3,1.22m x H25cm Coral Kids Pool,Introduce your little ones to the joy of swimm...,399.0,Blue / Free,41562104365265,140214-S23-51009,shopify,1-22m-x-h25cm-coral-kids-pool,False,https://www.ninoskids.com/en/products/1-22m-x-...,2026/02/23 02:06:06 PM,1.22m x H25cm Coral Kids Pool - Blue / Free: I...
4,1.34m x 1.42m Fantasy Dragon Ride On,Get ready for an epic adventure with our 1.34m...,799.0,Green / Free,41562101973201,140214-S23-41476,shopify,1-34m-x-1-42m-fantasy-dragon-ride-on,False,https://www.ninoskids.com/en/products/1-34m-x-...,2026/02/23 02:06:05 PM,1.34m x 1.42m Fantasy Dragon Ride On - Green /...
...,...,...,...,...,...,...,...,...,...,...,...,...
1775,كوب مانع للتسرب+6,"Introducing our leak-proof cup, a must-have fo...",350.0,Blue / Free,42898370986193,414-S22-35/208,shopify,%D9%83%D9%88%D8%A8-%D9%85%D8%A7%D9%86%D8%B9-%D...,True,https://www.ninoskids.com/en/products/%D9%83%D...,2026/02/23 02:35:36 PM,كوب مانع للتسرب+6 - Blue / Free: Introducing o...
1776,كوب مانع للتسرب+6,"Introducing our leak-proof cup, a must-have fo...",400.0,Pink / Free,42898370953425,414-S22-35/208,shopify,%D9%83%D9%88%D8%A8-%D9%85%D8%A7%D9%86%D8%B9-%D...,True,https://www.ninoskids.com/en/products/%D9%83%D...,2026/02/23 02:35:36 PM,كوب مانع للتسرب+6 - Pink / Free: Introducing o...
1777,ماصة طعام,-3 YearsIntroduce your little one to the delic...,310.0,6M,42257066918097,435-R21-207,shopify,%D9%85%D8%A7%D8%B5%D8%A9-%D8%B7%D8%B9%D8%A7%D9%85,True,https://www.ninoskids.com/en/products/%D9%85%D...,2026/02/23 02:35:32 PM,ماصة طعام - 6M: -3 YearsIntroduce your little ...
1778,ماصة فواكه سيليكون بيد طويلة بالغيار من ترو,Size Introducing the perfect solution for feed...,235.0,Mix Color / Free,41512960524497,414-R23-2022017TR,shopify,%D9%85%D8%A7%D8%B5%D8%A9-%D9%81%D9%88%D8%A7%D9...,True,https://www.ninoskids.com/en/products/%D9%85%D...,2026/02/23 02:35:30 PM,ماصة فواكه سيليكون بيد طويلة بالغيار من ترو - ...
1779,وسائد ثدي ترو القطنية 30 قطعة,"Introducing the Tru Cotton Breast Pads, a must...",190.0,Mix Color / Free,41512961474769,414-R23-18920TR,shopify,%D9%88%D8%B3%D8%A7%D8%A6%D8%AF-%D8%AB%D8%AF%D9...,True,https://www.ninoskids.com/en/products/%D9%88%D...,2026/02/23 02:35:41 PM,وسائد ثدي ترو القطنية 30 قطعة - Mix Color / F...

In [6]:
'''
Products Table
'''
df_products = df_merged
df_products = df_products.drop(columns=['Variant ID', 'Availability'])

# Split by comma and strip whitespace from each element
# 1. First, split the strings into lists (if you haven't already)
df_products['SKUs'] = df_products['SKU'].str.split(',')

# 2. Grab the first element of each list and strip whitespace
df_products['SKU'] = df_products['SKUs'].str[0].str.strip()
# 1. Clean up the decimals and whitespace within the lists first
# This removes '.0' and extra spaces from every item in every list
df_products['SKUs'] = df_products['SKUs'].apply(lambda x: [i.replace('.0', '').strip() for i in x])

# 2. Join the list elements into a single string separated by a space
df_products['SKUs'] = df_products['SKUs'].str.join(' ')

df_products.to_csv(r'C:\Users\moham\WebScraping\legacy_app\output\ninos_kids\ninos_products.csv', index=False)
df_products.columns

Index(['Product', 'Description', 'Price', 'Variant', 'SKU',
       'Inventory Management', 'Handle', 'Product URL', 'Scraped at',
       'Hollistic Description', 'SKUs'],
      dtype='object')