In [2]:
'''
Loading Master Tables
'''
import pandas as pd

df_heba_compact = pd.read_csv(r"C:\Users\moham\OneDrive\Desktop\WebScraping\legacy_app\output\heba\heba_compact_view.csv")
df_nillens_compact = pd.read_csv(r"C:\Users\moham\OneDrive\Desktop\WebScraping\legacy_app\output\Nillens\nillens_compact_view.csv")
df_lilly_compact = pd.read_csv(r"C:\Users\moham\OneDrive\Desktop\WebScraping\legacy_app\output\Lilly Home\lilly_home_compact_view.csv")
df_applemint_compact = pd.read_csv(r"C:\Users\moham\OneDrive\Desktop\WebScraping\legacy_app\output\applemint\applemint_compact.csv")

In [5]:
'''
Create the Master Table 
'''
df_heba_compact["Brand"] = "Heba Linens"
df_nillens_compact["Brand"] = "Nillens"
df_lilly_compact["Brand"] = "Lilly Home"
df_combined = pd.concat([df_heba_compact, df_nillens_compact, df_lilly_compact, df_applemint_compact], ignore_index=True)
df_combined.to_csv(r"C:\Users\moham\OneDrive\Desktop\WebScraping\legacy_app\output\all\all_products_compact.csv", index=False)
df_combined

,Product,Variant,Price,Handle,Inventory Management,Variant ID,Availability,SKU,Product URL,Scraped at,Description,Hollistic Description,Brand
0,Astronauts - Swaddle Towel sets,"White, Cream",995.0,astronauts-swaddle-towel-sets,shopify,"46383258698019, 46383258763555",False,"672b9440b801c, 672b943fec8b4",https://hebalinens.com/products/astronauts-swa...,2026/02/11 03:44:43 PM,Snuggle your little space explorer with our As...,"Astronauts - Swaddle Towel sets - White, Cream...",Heba Linens
1,Atraction - Pouch,Grey / 14 L X 18 W,495.0,atraction-pouch,shopify,54675384008995,True,NaN,https://hebalinens.com/products/atraction-pouch,2026/02/11 03:44:40 PM,This charming Pouch instantly adds a touch of ...,Atraction - Pouch - Grey / 14 L X 18 W: This c...,Heba Linens
2,Baby animals - Swaddle Towel sets,"White, Cream",995.0,baby-animals-swaddle-towel-sets,shopify,"46383232647459, 46383232712995",False,"672b9440b0b7a, 672b943fe31db",https://hebalinens.com/products/baby-animals-s...,2026/02/11 03:44:47 PM,"Soft and cuddly, this baby swaddle towel set w...","Baby animals - Swaddle Towel sets - White, Cre...",Heba Linens
3,Ballerina - Bath robe,4 years to 6 years / White,645.0,ballerina-bath-robe,shopify,46381868187939,True,672b943feffbe,https://hebalinens.com/products/ballerina-bath...,2026/02/11 03:44:48 PM,"Introducing Ballerina, the perfect 100% cotton...",Ballerina - Bath robe - 4 years to 6 years / W...,Heba Linens
4,Ballerina - Bath robe,6 years to 8 years / White,945.0,ballerina-bath-robe,shopify,46381868253475,False,672b9440ad92d,https://hebalinens.com/products/ballerina-bath...,2026/02/11 03:44:48 PM,"Introducing Ballerina, the perfect 100% cotton...",Ballerina - Bath robe - 6 years to 8 years / W...,Heba Linens
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1802,Unisex Fleece Cargo Double Pocket Jogger Pants...,"2-3, 3-4, 4-5, 6-7, 8-9, 10-11, 12-13",650.0,unisex-fleece-cargo-double-pocket-jogger-pants...,shopify,"45912880611577, 45912880644345, 45912880677113...",True,NaN,https://applemintandcocoa.com//products/unisex...,2026/02/22 12:59:34 PM,Key Features: 100% Cotton Fleece brushed insid...,Unisex Fleece Cargo Double Pocket Jogger Pants...,NaN
1803,Unisex Fleece Cargo Jogger Pants in Mustard,"12-18M, 2-3, 3-4, 4-5, 6-7, 8-9, 10-11, 12-13",650.0,unisex-fleece-cargo-jogger-pants-in-havan,shopify,"44068257366265, 44068256579833, 44068256612601...",True,NaN,https://applemintandcocoa.com//products/unisex...,2026/02/22 12:59:27 PM,Key Features: 100% Cotton Fleece brushed insid...,Unisex Fleece Cargo Jogger Pants in Mustard - ...,NaN
1804,White Cargo Girls Shorts,"2-3 Years / Shorts Only, 3-4 Years / Shorts On...",399.0,white-girls-shorts,shopify,"43732626309369, 43732626342137, 43732626374905...",False,NaN,https://applemintandcocoa.com//products/white-...,2026/02/22 12:59:29 PM,Size & Fit: Regular fit. Runs true to size.Do ...,White Cargo Girls Shorts - 2-3 Years / Shorts ...,NaN
1805,Winner in Black Sports Shorts,"6-7, 8-9, 10-11, 12-13, 14-15",370.0,winner-sports-shorts,shopify,"46461419290873, 46461419323641, 46461419356409...",True,NaN,https://applemintandcocoa.com//products/winner...,2026/02/22 12:59:31 PM,"Introducing -PULSE- Comfortable, breathable sp...","Winner in Black Sports Shorts - 6-7, 8-9, 10-1...",NaN
1806,“Write your own 2.0” Kids Hoodie (HOODIE ONLY),"2-3, 3-4, 4-5, 5-6, 6-7, 8-9, 10-11, 12-13",750.0,write-your-own-kids-hoodie-in-pure-white-hoodi...,shopify,"43498399465721, 43498399498489, 43498399531257...",True,NaN,https://applemintandcocoa.com//products/write-...,2026/02/22 12:59:28 PM,The COOLEST gift idea! Gift this to a child an...,“Write your own 2.0” Kids Hoodie (HOODIE ONLY)...,NaN

In [7]:
'''
Loading Products
'''
import pandas as pd

df_heba = pd.read_csv(r"C:\Users\moham\OneDrive\Desktop\WebScraping\legacy_app\output\heba\heba_products.csv")
df_nillens = pd.read_csv(r"C:\Users\moham\OneDrive\Desktop\WebScraping\legacy_app\output\Nillens\nillens_products.csv")
df_lilly = pd.read_csv(r"C:\Users\moham\OneDrive\Desktop\WebScraping\legacy_app\output\Lilly Home\lilly_home_products.csv")
df_applemint = pd.read_csv(r"C:\Users\moham\OneDrive\Desktop\WebScraping\legacy_app\output\applemint\applemint_products.csv")
df_applemint

,Product,Price,Handle,Inventory Management,SKU,Product URL,Scraped at,Description,Hollistic Description,SKUs
0,Adventure Incomplete Washed Tee For Adults,519.0,adventure-incomplete-tee-for-adults,shopify,NaN,https://applemintandcocoa.com//products/advent...,2026/02/22 12:53:26 PM,Size & Fit:Oversized FitFabric:100% Cotton Dis...,Adventure Incomplete Washed Tee For Adults - M...,NaN
1,Adventure Incomplete Washed Tee For Kids,369.0,adventure-incomplete-washed-tee-for-kids,shopify,NaN,https://applemintandcocoa.com//products/advent...,2026/02/22 12:53:37 PM,Size & Fit: Oversized Fit Fabric: 100% Cotton ...,Adventure Incomplete Washed Tee For Kids - 2-3...,NaN
2,Aiming Higher in Olive Sports Tee,322.0,aiming-higher-in-olive-tee,shopify,NaN,https://applemintandcocoa.com//products/aiming...,2026/02/22 12:53:27 PM,"Introducing -PULSE- Comfortable, breathable sp...","Aiming Higher in Olive Sports Tee - 4-5, 6-7, ...",NaN
3,Airborne Unicorn,299.0,airborne-unicorn,shopify,NaN,https://applemintandcocoa.com//products/airbor...,2026/02/22 12:53:28 PM,Crafted in our soft cotton jersey. Perfect for...,"Airborne Unicorn - 2-3, 4-5, 6-7, 8-9, 10-11, ...",NaN
4,Airforce Sports Tee,299.0,airforce-tee,shopify,NaN,https://applemintandcocoa.com//products/airfor...,2026/02/22 12:53:36 PM,"Introducing -PULSE- Comfortable, breathable sp...","Airforce Sports Tee - 4-5, 6-7, 8-9, 10-11, 12...",NaN
...,...,...,...,...,...,...,...,...,...,...
689,Unisex Fleece Cargo Double Pocket Jogger Pants...,650.0,unisex-fleece-cargo-double-pocket-jogger-pants...,shopify,NaN,https://applemintandcocoa.com//products/unisex...,2026/02/22 12:59:34 PM,Key Features: 100% Cotton Fleece brushed insid...,Unisex Fleece Cargo Double Pocket Jogger Pants...,NaN
690,Unisex Fleece Cargo Jogger Pants in Mustard,650.0,unisex-fleece-cargo-jogger-pants-in-havan,shopify,NaN,https://applemintandcocoa.com//products/unisex...,2026/02/22 12:59:27 PM,Key Features: 100% Cotton Fleece brushed insid...,Unisex Fleece Cargo Jogger Pants in Mustard - ...,NaN
691,White Cargo Girls Shorts,399.0,white-girls-shorts,shopify,NaN,https://applemintandcocoa.com//products/white-...,2026/02/22 12:59:29 PM,Size & Fit: Regular fit. Runs true to size.Do ...,White Cargo Girls Shorts - 2-3 Years / Shorts ...,NaN
692,Winner in Black Sports Shorts,370.0,winner-sports-shorts,shopify,NaN,https://applemintandcocoa.com//products/winner...,2026/02/22 12:59:31 PM,"Introducing -PULSE- Comfortable, breathable sp...","Winner in Black Sports Shorts - 6-7, 8-9, 10-1...",NaN
693,“Write your own 2.0” Kids Hoodie (HOODIE ONLY),750.0,write-your-own-kids-hoodie-in-pure-white-hoodi...,shopify,NaN,https://applemintandcocoa.com//products/write-...,2026/02/22 12:59:28 PM,The COOLEST gift idea! Gift this to a child an...,“Write your own 2.0” Kids Hoodie (HOODIE ONLY)...,NaN

In [9]:
'''
Create in an all_products table 
'''
df_heba["Brand"] = "Heba Linens"
df_nillens["Brand"] = "Nillens"
df_lilly["Brand"] = "Lilly Home"
df_applemint["Brand"] = "Applemint and Cocao"
df_combined_products = pd.concat([df_heba, df_nillens, df_lilly, df_applemint], ignore_index=True)
df_combined_products

,Product,Price,Handle,Inventory Management,SKU,Product URL,Scraped at,Description,Hollistic Description,SKUs,Brand,Size
0,Astronauts - Swaddle Towel sets,995.0,astronauts-swaddle-towel-sets,shopify,672b9440b801c,https://hebalinens.com/products/astronauts-swa...,2026/02/11 03:44:43 PM,Snuggle your little space explorer with our As...,"Astronauts - Swaddle Towel sets - White, Cream...",672b9440b801c 672b943fec8b4,Heba Linens,NaN
1,Atraction - Pouch,495.0,atraction-pouch,shopify,NaN,https://hebalinens.com/products/atraction-pouch,2026/02/11 03:44:40 PM,This charming Pouch instantly adds a touch of ...,Atraction - Pouch - Grey / 14 L X 18 W: This c...,NaN,Heba Linens,NaN
2,Baby animals - Swaddle Towel sets,995.0,baby-animals-swaddle-towel-sets,shopify,672b9440b0b7a,https://hebalinens.com/products/baby-animals-s...,2026/02/11 03:44:47 PM,"Soft and cuddly, this baby swaddle towel set w...","Baby animals - Swaddle Towel sets - White, Cre...",672b9440b0b7a 672b943fe31db,Heba Linens,NaN
3,Ballerina - Bath robe,645.0,ballerina-bath-robe,shopify,672b943feffbe,https://hebalinens.com/products/ballerina-bath...,2026/02/11 03:44:48 PM,"Introducing Ballerina, the perfect 100% cotton...",Ballerina - Bath robe - 4 years to 6 years / W...,672b943feffbe,Heba Linens,NaN
4,Ballerina - Bath robe,945.0,ballerina-bath-robe,shopify,672b9440ad92d,https://hebalinens.com/products/ballerina-bath...,2026/02/11 03:44:48 PM,"Introducing Ballerina, the perfect 100% cotton...",Ballerina - Bath robe - 6 years to 8 years / W...,672b9440ad92d,Heba Linens,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
1802,Unisex Fleece Cargo Double Pocket Jogger Pants...,650.0,unisex-fleece-cargo-double-pocket-jogger-pants...,shopify,NaN,https://applemintandcocoa.com//products/unisex...,2026/02/22 12:59:34 PM,Key Features: 100% Cotton Fleece brushed insid...,Unisex Fleece Cargo Double Pocket Jogger Pants...,NaN,Applemint and Cocao,NaN
1803,Unisex Fleece Cargo Jogger Pants in Mustard,650.0,unisex-fleece-cargo-jogger-pants-in-havan,shopify,NaN,https://applemintandcocoa.com//products/unisex...,2026/02/22 12:59:27 PM,Key Features: 100% Cotton Fleece brushed insid...,Unisex Fleece Cargo Jogger Pants in Mustard - ...,NaN,Applemint and Cocao,NaN
1804,White Cargo Girls Shorts,399.0,white-girls-shorts,shopify,NaN,https://applemintandcocoa.com//products/white-...,2026/02/22 12:59:29 PM,Size & Fit: Regular fit. Runs true to size.Do ...,White Cargo Girls Shorts - 2-3 Years / Shorts ...,NaN,Applemint and Cocao,NaN
1805,Winner in Black Sports Shorts,370.0,winner-sports-shorts,shopify,NaN,https://applemintandcocoa.com//products/winner...,2026/02/22 12:59:31 PM,"Introducing -PULSE- Comfortable, breathable sp...","Winner in Black Sports Shorts - 6-7, 8-9, 10-1...",NaN,Applemint and Cocao,NaN
1806,“Write your own 2.0” Kids Hoodie (HOODIE ONLY),750.0,write-your-own-kids-hoodie-in-pure-white-hoodi...,shopify,NaN,https://applemintandcocoa.com//products/write-...,2026/02/22 12:59:28 PM,The COOLEST gift idea! Gift this to a child an...,“Write your own 2.0” Kids Hoodie (HOODIE ONLY)...,NaN,Applemint and Cocao,NaN

In [10]:
def remove_duplicate_products(df):
    """
    Removes rows where the combination of Brand and Handle is repeated.
    Keeps the first occurrence and removes subsequent ones.
    """
    # subset: the columns to check for duplicates
    # keep: 'first' keeps the first instance, 'last' keeps the last, False drops all duplicates
    df_cleaned = df.drop_duplicates(subset=['Brand', 'Handle'], keep='first')
    
    # Optional: Reset the index since rows were removed
    df_cleaned = df_cleaned.reset_index(drop=True)
    
    return df_cleaned

In [11]:
# Apply the function
df_combined_products_clean = remove_duplicate_products(df_combined_products)

# Display result
print(f"Total rows after removing duplicates: {df_combined_products_clean.shape[0]}. Rows removed {df_combined_products.shape[0]-df_combined_products_clean.shape[0]}")

Total rows after removing duplicates: 1411. Rows removed 396

In [12]:
df_combined_products_clean.to_csv(r"C:\Users\moham\OneDrive\Desktop\WebScraping\legacy_app\output\all\all_products.csv")
df_combined_products.to_csv(r"C:\Users\moham\OneDrive\Desktop\WebScraping\legacy_app\output\all\all_products_unclean.csv")

In [13]:
'''
Loading Variants
'''
import pandas as pd

df_heba = pd.read_csv(r"C:\Users\moham\OneDrive\Desktop\WebScraping\legacy_app\output\heba\heba_variants.csv")
df_nillens = pd.read_csv(r"C:\Users\moham\OneDrive\Desktop\WebScraping\legacy_app\output\Nillens\nillens_variants.csv")
df_lilly = pd.read_csv(r"C:\Users\moham\OneDrive\Desktop\WebScraping\legacy_app\output\Lilly Home\lilly_home_variants.csv")
df_applemint = pd.read_csv(r"C:\Users\moham\OneDrive\Desktop\WebScraping\legacy_app\output\applemint\applemint_variants.csv")
df_applemint

,Variant ID,Handle,Variant,Price,SKU,Scraped at,Availability,Inventory Management
0,46473465069817,adventure-incomplete-tee-for-adults,Medium / T-shirt Only,519.0,NaN,2026/02/22 12:53:26 PM,False,shopify
1,46473465102585,adventure-incomplete-tee-for-adults,Large / T-shirt Only,519.0,NaN,2026/02/22 12:53:26 PM,False,shopify
2,46473465135353,adventure-incomplete-tee-for-adults,X-Large / T-shirt Only,519.0,NaN,2026/02/22 12:53:26 PM,True,shopify
3,46473465168121,adventure-incomplete-tee-for-adults,XX-Large / T-shirt Only,519.0,NaN,2026/02/22 12:53:26 PM,True,shopify
4,46516044366073,aiming-higher-in-olive-tee,4-5,322.0,NaN,2026/02/22 12:53:27 PM,True,shopify
...,...,...,...,...,...,...,...,...
4040,46461443375353,twirl-in-powder-pink-girls-tee,6-7,322.0,NaN,2026/02/22 12:59:37 PM,True,shopify
4041,46461443408121,twirl-in-powder-pink-girls-tee,8-9,322.0,NaN,2026/02/22 12:59:37 PM,True,shopify
4042,46461443440889,twirl-in-powder-pink-girls-tee,10-11,322.0,NaN,2026/02/22 12:59:37 PM,False,shopify
4043,46461443473657,twirl-in-powder-pink-girls-tee,12-13,322.0,NaN,2026/02/22 12:59:37 PM,True,shopify
4044,46461443506425,twirl-in-powder-pink-girls-tee,14-15,322.0,NaN,2026/02/22 12:59:37 PM,True,shopify

In [14]:
'''
Save variants in a all_variants table 
'''
df_heba["Brand"] = "Heba Linens"
df_nillens["Brand"] = "Nillens"
df_lilly["Brand"] = "Lilly Home"
df_applemint["Brand"] = "Applemint"
df_combined_variants = pd.concat([df_heba, df_nillens, df_lilly, df_applemint], ignore_index=True)
df_combined_variants

,Variant ID,Handle,Variant,Price,SKU,Scraped at,Availability,Color,Inventory Management,Brand
0,46353877205283,bra-and-underwear-bag,White / 60 L X 40 W,395.0,672b944f4d8e4,2026/02/11 03:44:25 PM,True,White,shopify,Heba Linens
1,46867430703395,flow-towels-set,White,2195.0,672b95f9ce279,2026/02/11 03:44:26 PM,False,White,shopify,Heba Linens
2,46867430768931,flow-towels-set,Grey,2195.0,672b95f9218be,2026/02/11 03:44:26 PM,False,Grey,shopify,Heba Linens
3,46336742719779,calligraphy-duvet-set,King / White,14495.0,672b94526d860,2026/02/11 03:44:27 PM,False,White,shopify,Heba Linens
4,46344867905827,table-cloth-batterflies,2.75 L x 1.8 W with 8 Napkin / Cream,6245.0,672b9451e57ce,2026/02/11 03:44:29 PM,True,Cream,shopify,Heba Linens
...,...,...,...,...,...,...,...,...,...,...
6703,46461443375353,twirl-in-powder-pink-girls-tee,6-7,322.0,NaN,2026/02/22 12:59:37 PM,True,NaN,shopify,Applemint
6704,46461443408121,twirl-in-powder-pink-girls-tee,8-9,322.0,NaN,2026/02/22 12:59:37 PM,True,NaN,shopify,Applemint
6705,46461443440889,twirl-in-powder-pink-girls-tee,10-11,322.0,NaN,2026/02/22 12:59:37 PM,False,NaN,shopify,Applemint
6706,46461443473657,twirl-in-powder-pink-girls-tee,12-13,322.0,NaN,2026/02/22 12:59:37 PM,True,NaN,shopify,Applemint
6707,46461443506425,twirl-in-powder-pink-girls-tee,14-15,322.0,NaN,2026/02/22 12:59:37 PM,True,NaN,shopify,Applemint

In [15]:
df_variants_final = df_combined_variants.drop_duplicates(subset=['Variant ID', 'Brand'], keep='first')
df_variants_final.to_csv(r"C:\Users\moham\OneDrive\Desktop\WebScraping\legacy_app\output\all\all_variants.csv")