In [2]:
import pandas as pd

df = pd.read_csv(r"C:\Users\moham\OneDrive\Desktop\WebScraping\legacy_app\output\all\all_products.csv")
df = df.iloc[:, 1:]
df

,Product,Price,Handle,Inventory Management,SKU,Product URL,Scraped at,Description,Hollistic Description,SKUs,Brand,Size
0,Astronauts - Swaddle Towel sets,995.0,astronauts-swaddle-towel-sets,shopify,672b9440b801c,https://hebalinens.com/products/astronauts-swa...,2026/02/11 03:44:43 PM,Snuggle your little space explorer with our As...,"Astronauts - Swaddle Towel sets - White, Cream...",672b9440b801c 672b943fec8b4,Heba Linens,NaN
1,Atraction - Pouch,495.0,atraction-pouch,shopify,NaN,https://hebalinens.com/products/atraction-pouch,2026/02/11 03:44:40 PM,This charming Pouch instantly adds a touch of ...,Atraction - Pouch - Grey / 14 L X 18 W: This c...,NaN,Heba Linens,NaN
2,Baby animals - Swaddle Towel sets,995.0,baby-animals-swaddle-towel-sets,shopify,672b9440b0b7a,https://hebalinens.com/products/baby-animals-s...,2026/02/11 03:44:47 PM,"Soft and cuddly, this baby swaddle towel set w...","Baby animals - Swaddle Towel sets - White, Cre...",672b9440b0b7a 672b943fe31db,Heba Linens,NaN
3,Ballerina - Bath robe,645.0,ballerina-bath-robe,shopify,672b943feffbe,https://hebalinens.com/products/ballerina-bath...,2026/02/11 03:44:48 PM,"Introducing Ballerina, the perfect 100% cotton...",Ballerina - Bath robe - 4 years to 6 years / W...,672b943feffbe,Heba Linens,NaN
4,Ballerina - Duvet set,6395.0,ballerina-duvet-set,shopify,672b9442c140d,https://hebalinens.com/products/ballerina-duve...,2026/02/11 03:44:36 PM,Let your dreams take flight with this Ballerin...,Ballerina - Duvet set - White: Let your dreams...,672b9442c140d,Heba Linens,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
1049,knitted Set,2280.0,knitted-set,shopify,NaN,https://eg.lilly-home.com//products/knitted-set,2026/02/11 04:43:35 PM,2 pieces knittedlounge wear set :-,"knitted Set - small / white, small / Beige, me...",NaN,Lilly Home,NaN
1050,lines duvet cover Set (3pcs),4620.0,lines-duvet-cover-set-3pcs,NaN,NaN,https://eg.lilly-home.com//products/lines-duve...,2026/02/11 04:44:20 PM,A 3 piece400 thread count 100% egyptian cott...,"lines duvet cover Set (3pcs) - king / white, k...",NaN,Lilly Home,NaN
1051,stones duvet cover Set (3pcs),4620.0,stones-duvet-cover-set-3pcs,NaN,NaN,https://eg.lilly-home.com//products/stones-duv...,2026/02/11 04:45:16 PM,A 3 piece400 thread count 100% egyptian cott...,"stones duvet cover Set (3pcs) - king / white, ...",NaN,Lilly Home,NaN
1052,tri duvet cover Set (3pcs),4620.0,tri-duvet-cover-set-3pcs,NaN,NaN,https://eg.lilly-home.com//products/tri-duvet-...,2026/02/11 04:45:38 PM,A 3 piece400 thread count 100% egyptian cotto...,"tri duvet cover Set (3pcs) - king / white, kin...",NaN,Lilly Home,NaN
1053,zigzag 78 Towel set (3 pcs),1880.0,zigzag-78-towel-set-6-pcs,NaN,NaN,https://eg.lilly-home.com//products/zigzag-78-...,2026/02/11 04:45:49 PM,A 100% Egyptian Cotton High absorption 3 piece...,"zigzag 78 Towel set (3 pcs) - white, silver, c...",NaN,Lilly Home,NaN

In [3]:
df['Brand + Handle'] = df["Brand"] + ' ' + df["Handle"]
df.to_csv(r"C:\Users\moham\OneDrive\Desktop\WebScraping\legacy_app\output\all\all_products_clean.csv", index=False)
df

,Product,Price,Handle,Inventory Management,SKU,Product URL,Scraped at,Description,Hollistic Description,SKUs,Brand,Size,Brand + Handle
0,Astronauts - Swaddle Towel sets,995.0,astronauts-swaddle-towel-sets,shopify,672b9440b801c,https://hebalinens.com/products/astronauts-swa...,2026/02/11 03:44:43 PM,Snuggle your little space explorer with our As...,"Astronauts - Swaddle Towel sets - White, Cream...",672b9440b801c 672b943fec8b4,Heba Linens,NaN,Heba Linens astronauts-swaddle-towel-sets
1,Atraction - Pouch,495.0,atraction-pouch,shopify,NaN,https://hebalinens.com/products/atraction-pouch,2026/02/11 03:44:40 PM,This charming Pouch instantly adds a touch of ...,Atraction - Pouch - Grey / 14 L X 18 W: This c...,NaN,Heba Linens,NaN,Heba Linens atraction-pouch
2,Baby animals - Swaddle Towel sets,995.0,baby-animals-swaddle-towel-sets,shopify,672b9440b0b7a,https://hebalinens.com/products/baby-animals-s...,2026/02/11 03:44:47 PM,"Soft and cuddly, this baby swaddle towel set w...","Baby animals - Swaddle Towel sets - White, Cre...",672b9440b0b7a 672b943fe31db,Heba Linens,NaN,Heba Linens baby-animals-swaddle-towel-sets
3,Ballerina - Bath robe,645.0,ballerina-bath-robe,shopify,672b943feffbe,https://hebalinens.com/products/ballerina-bath...,2026/02/11 03:44:48 PM,"Introducing Ballerina, the perfect 100% cotton...",Ballerina - Bath robe - 4 years to 6 years / W...,672b943feffbe,Heba Linens,NaN,Heba Linens ballerina-bath-robe
4,Ballerina - Duvet set,6395.0,ballerina-duvet-set,shopify,672b9442c140d,https://hebalinens.com/products/ballerina-duve...,2026/02/11 03:44:36 PM,Let your dreams take flight with this Ballerin...,Ballerina - Duvet set - White: Let your dreams...,672b9442c140d,Heba Linens,NaN,Heba Linens ballerina-duvet-set
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1049,knitted Set,2280.0,knitted-set,shopify,NaN,https://eg.lilly-home.com//products/knitted-set,2026/02/11 04:43:35 PM,2 pieces knittedlounge wear set :-,"knitted Set - small / white, small / Beige, me...",NaN,Lilly Home,NaN,Lilly Home knitted-set
1050,lines duvet cover Set (3pcs),4620.0,lines-duvet-cover-set-3pcs,NaN,NaN,https://eg.lilly-home.com//products/lines-duve...,2026/02/11 04:44:20 PM,A 3 piece400 thread count 100% egyptian cott...,"lines duvet cover Set (3pcs) - king / white, k...",NaN,Lilly Home,NaN,Lilly Home lines-duvet-cover-set-3pcs
1051,stones duvet cover Set (3pcs),4620.0,stones-duvet-cover-set-3pcs,NaN,NaN,https://eg.lilly-home.com//products/stones-duv...,2026/02/11 04:45:16 PM,A 3 piece400 thread count 100% egyptian cott...,"stones duvet cover Set (3pcs) - king / white, ...",NaN,Lilly Home,NaN,Lilly Home stones-duvet-cover-set-3pcs
1052,tri duvet cover Set (3pcs),4620.0,tri-duvet-cover-set-3pcs,NaN,NaN,https://eg.lilly-home.com//products/tri-duvet-...,2026/02/11 04:45:38 PM,A 3 piece400 thread count 100% egyptian cotto...,"tri duvet cover Set (3pcs) - king / white, kin...",NaN,Lilly Home,NaN,Lilly Home tri-duvet-cover-set-3pcs
1053,zigzag 78 Towel set (3 pcs),1880.0,zigzag-78-towel-set-6-pcs,NaN,NaN,https://eg.lilly-home.com//products/zigzag-78-...,2026/02/11 04:45:49 PM,A 100% Egyptian Cotton High absorption 3 piece...,"zigzag 78 Towel set (3 pcs) - white, silver, c...",NaN,Lilly Home,NaN,Lilly Home zigzag-78-towel-set-6-pcs