In [15]:
import pandas as pd
file = r'C:\Users\moham\OneDrive\Desktop\WebScraping\legacy_app\output\Triconuts\triconuts.csv'
df = pd.read_csv(file)
df = df.drop(columns=['Weight'])
df = df.dropna(subset=['Description'])
df

,Product,Handle,Price,SKU,Availability,Variant Title,Variant ID,Inventory Management,Product URL,Scraped at,Description
0,Ballerina Dreams Set,ballerina-dreams-set-1,1859.0,NaN,True,Default Title,51058187436330,shopify,https://www.triconuts.com//products/ballerina-...,2026/02/22 02:05:08 PM,Ballerina Dreams Set 🩰 A dreamy handmade gift ...
1,Cat Toy,cat-toy-no-name,557.0,NaN,False,Default Title,47843545121066,shopify,https://www.triconuts.com//products/cat-toy-no...,2026/02/22 02:05:09 PM,Hand-crocheted amigurumi cat plush toy in ligh...
2,Blue Velvet Blanket (Super Soft),blue-velvet-blanket-super-soft,1259.0,NaN,True,Default Title,51012227006762,shopify,https://www.triconuts.com//products/blue-velve...,2026/02/22 02:05:09 PM,Designed and handmade in Egypt For customized ...
3,Beige Girl Bunny Toy,girl-bunny-toy-2,499.0,NaN,True,Default Title,44188819292458,shopify,https://www.triconuts.com//products/girl-bunny...,2026/02/22 02:05:10 PM,Handmade 25 cm crochet bunny – the perfect sof...
4,Dinosaur Toy (Extra Soft),dinosaur-toy-extra-soft,879.0,NaN,True,Default Title,49933380845866,shopify,https://www.triconuts.com//products/dinosaur-t...,2026/02/22 02:05:11 PM,100% handcrafted Safe for babies & kids Materi...
...,...,...,...,...,...,...,...,...,...,...,...
93,White Girl Bunny Toy,girl-bunny-toy,499.0,NaN,True,Default Title,44188791144746,shopify,https://www.triconuts.com//products/girl-bunny...,2026/02/22 02:06:29 PM,"Soft handmade crochet bunny, 25 cm tall — perf..."
94,Winter Blue Scarf (EXTRA SOFT),winter-blue-scarf-extra-soft,539.0,NaN,True,Default Title,51039242780970,shopify,https://www.triconuts.com//products/winter-blu...,2026/02/22 02:06:30 PM,Soft Knit Baby Scarf – Cozy & Cute Winter Esse...
95,White Boy Bunny Toy,boy-bunny-toy,499.0,NaN,True,Default Title,44188844785962,shopify,https://www.triconuts.com//products/boy-bunny-toy,2026/02/22 02:06:31 PM,Handmade 25 cm crochet bunny with a blue bow t...
96,Yellow Velvet Blanket (Super Soft),yellow-velvet-blanket-super-soft,1259.0,NaN,True,Default Title,51012246372650,shopify,https://www.triconuts.com//products/yellow-vel...,2026/02/22 02:06:32 PM,Designed and handmade in Egypt For customized ...
97,White Velvet Blanket (Super Soft),white-velvet-blanket-super-soft,1259.0,NaN,True,Default Title,51012290117930,shopify,https://www.triconuts.com//products/white-velv...,2026/02/22 02:06:33 PM,Designed and handmade in Egypt For customized ...

In [16]:
import pandas as pd

# 1. Clean the 'Description' column BEFORE merging to remove new lines
df['Description'] = df['Description'].str.replace(r'\n|\r', ' ', regex=True)

# 2. Updated aggregation rules to create clean strings instead of Python lists
# We use ', '.join() to make "White, Cream" instead of "['White', 'Cream']"
aggregation_rules = {
    # 'Title': lambda x: ', '.join(map(str, x.unique())),
    # 'Variant': lambda x: ', '.join(map(str, x.unique())), 
    'Variant ID': lambda x: ', '.join(map(str, x.unique())),
    'SKU': lambda x: ', '.join(map(str, x.unique())),
    # 'Size': lambda x: ', '.join(map(str, x.unique())),
    'Inventory Management': 'first',
    'Handle': 'first',
    'Availability': 'first',
    'Product URL': 'first',
    'Scraped at': 'first'
}

# Group by the "Core" identity
df_merged = df.groupby(['Product', 'Description', 'Price'], as_index=False).agg(aggregation_rules)

# 3. FIX: Create the Hollistic Description correctly
# Use .astype(str) instead of str() to handle it row-by-row
df_merged['Hollistic Description'] = (
    df_merged['Product'] + 
    # ' - ' + 
    # df_merged['Variant'].astype(str) + 
    ": " + 
    df_merged["Description"]
)

# Save to CSV (index=False prevents that extra "0, 1, 2" column at the start)
print(df_merged.columns)
df_merged.to_csv(r'C:\Users\moham\OneDrive\Desktop\WebScraping\legacy_app\output\Triconuts\triconuts_compact.csv', index=False)
df_merged

Index(['Product', 'Description', 'Price', 'Variant ID', 'SKU',
       'Inventory Management', 'Handle', 'Availability', 'Product URL',
       'Scraped at', 'Hollistic Description'],
      dtype='object')

,Product,Description,Price,Variant ID,SKU,Inventory Management,Handle,Availability,Product URL,Scraped at,Hollistic Description
0,Baby Boy Besties Set,Baby Boy Besties Set The Baby Boy Besties Set ...,969.0,51058266997034,nan,shopify,baby-boy-besties-set-1,True,https://www.triconuts.com//products/baby-boy-b...,2026/02/22 02:05:21 PM,Baby Boy Besties Set: Baby Boy Besties Set The...
1,Bakar Doll,Meet our handcrafted Bakar Toy – a premium cro...,1199.0,51164360278314,nan,shopify,bakar-toy,True,https://www.triconuts.com//products/bakar-toy,2026/02/22 02:05:31 PM,Bakar Doll: Meet our handcrafted Bakar Toy – a...
2,Ballerina Dreams Set,Ballerina Dreams Set 🩰 A dreamy handmade gift ...,1859.0,51058187436330,nan,shopify,ballerina-dreams-set-1,True,https://www.triconuts.com//products/ballerina-...,2026/02/22 02:05:08 PM,Ballerina Dreams Set: Ballerina Dreams Set 🩰 A...
3,Ballerina Toy,"Adorable handmade crocheted ballerina doll, 27...",599.0,49974051635498,nan,shopify,ballerina-toy,True,https://www.triconuts.com//products/ballerina-toy,2026/02/22 02:05:20 PM,Ballerina Toy: Adorable handmade crocheted bal...
4,Beige Boy Bunny Toy,Handmade 25 cm crochet bunny with a blue bow t...,499.0,44188834431274,nan,shopify,boy-bunny-toy-2,True,https://www.triconuts.com//products/boy-bunny-...,2026/02/22 02:05:29 PM,Beige Boy Bunny Toy: Handmade 25 cm crochet bu...
...,...,...,...,...,...,...,...,...,...,...,...
71,Xmas Gift Card,🎁Triconuts Gift Card Give the gift of choice! ...,250.0,50900945436970,nan,None,xmas-gift-card,True,https://www.triconuts.com//products/xmas-gift-...,2026/02/22 02:06:28 PM,Xmas Gift Card: 🎁Triconuts Gift Card Give the ...
72,Xmas Gift Card,🎁Triconuts Gift Card Give the gift of choice! ...,500.0,50900945469738,nan,None,xmas-gift-card,True,https://www.triconuts.com//products/xmas-gift-...,2026/02/22 02:06:28 PM,Xmas Gift Card: 🎁Triconuts Gift Card Give the ...
73,Xmas Gift Card,🎁Triconuts Gift Card Give the gift of choice! ...,1000.0,50900945502506,nan,None,xmas-gift-card,True,https://www.triconuts.com//products/xmas-gift-...,2026/02/22 02:06:28 PM,Xmas Gift Card: 🎁Triconuts Gift Card Give the ...
74,Xmas Special Packaging,Want to get your order in a cute xmas package?...,50.0,50904546509098,nan,None,xmas-special-package,True,https://www.triconuts.com//products/xmas-speci...,2026/02/22 02:06:25 PM,Xmas Special Packaging: Want to get your order...
75,Yellow Velvet Blanket (Super Soft),Designed and handmade in Egypt For customized ...,1259.0,51012246372650,nan,shopify,yellow-velvet-blanket-super-soft,True,https://www.triconuts.com//products/yellow-vel...,2026/02/22 02:06:32 PM,Yellow Velvet Blanket (Super Soft): Designed a...

In [17]:
'''
Products Table
'''
df_products = df_merged
df_products = df_products.drop(columns=['Variant ID', 'Availability'])

# Split by comma and strip whitespace from each element
# 1. First, split the strings into lists (if you haven't already)
df_products['SKUs'] = df_products['SKU'].str.split(',')

# 2. Grab the first element of each list and strip whitespace
df_products['SKU'] = df_products['SKUs'].str[0].str.strip()
# 1. Clean up the decimals and whitespace within the lists first
# This removes '.0' and extra spaces from every item in every list
df_products['SKUs'] = df_products['SKUs'].apply(lambda x: [i.replace('.0', '').strip() for i in x])

# 2. Join the list elements into a single string separated by a space
df_products['SKUs'] = df_products['SKUs'].str.join(' ')

df_products.to_csv(r'C:\Users\moham\OneDrive\Desktop\WebScraping\legacy_app\output\Triconuts\triconuts_products.csv', index=False)
df_products.columns

Index(['Product', 'Description', 'Price', 'SKU', 'Inventory Management',
       'Handle', 'Product URL', 'Scraped at', 'Hollistic Description', 'SKUs'],
      dtype='object')